### ISSUE TITLE
新年快乐！顺便chrome无法安装新版本1.0.16

### ISSUE THREAD

**Issue by ricekiller** [esterTion/AcFun-HTML5-Player#10]
应用商店无法直接添加，从github下载crx文件也无法安装，提示：
Required value 'version' is missing or invalid.It must be between 1-4 dot-separated integers each between 0 and 65536。
chrome版本：63.0.3239.108。
没有安装其它插件。
firefox插件经过测试显示正常，番剧可以正常选集。

**Comment by esterTion** [comment]
我下午脚本提交更新的时候打成`1.0.16.1.`了，然后api接受了还发布了，我以为没问题就没再实验
版本号有效性验证在客户端也是坑
重新提交了个1.0.16.2

**Comment by ricekiller** [comment]
(＾o＾)ﾉ麻烦你了，更新强迫症非常满足

**Comment by esterTion** [comment]
没事，我这就是一行代码的事
![qq 20171231232928](https://user-images.githubusercontent.com/7265411/34462620-bcb84996-ee82-11e7-9de6-4cb4ba5f58dd.png)

新年快乐！
