### ISSUE TITLE
播放错误，type:"NetworkError"

### ISSUE THREAD

**Issue by WangHongshuo** [esterTion/AcFun-HTML5-Player#12]
最近好几天一直这个情况，是A站又炸了吗？
firefox 58.0.1 (64 位)
```
播放错误
{
  "type": "NetworkError",
  "info": "HttpStatusCodeInvalid",
  "detail": {
    "code": 403,
    "msg": "Forbidden"
  }
}
```

**Comment by esterTion** [comment]
试了下没问题啊

**Comment by WangHongshuo** [comment]
还是有问题，A站所有视频都放不了。难道是运营商的问题？

名称:	以太网
描述:	Realtek PCIe GBE Family Controller
物理地址(MAC):
状态:	可操作
最大传输单元:	1500
链接速度(接收/传输):	100/100 (Mbps)
DHCP 已启用:	是
DHCP 服务器:	192.168.3.1
DHCP 租约获得时间:	‎2018‎年‎1‎月‎31‎日 ‎星期三 14:11:52
DHCP 租约到期时间:	‎2018‎年‎2‎月‎1‎日 ‎星期四 14:11:52
IPv4 地址:	192.168.3.107/24
IPv6 地址:
默认网关:	192.168.3.1
DNS 服务器:	223.5.5.5, 223.6.6.6
DNS 域名:	
DNS 连接后缀:	
DNS 搜索后缀列表:	
网络名称:	网络  4
网络类别:	公共
连接性(IPv4/IPv6):	已连接到 Internet / 已连接到 未知网络

**Comment by WangHongshuo** [comment]
http://www.acfun.cn/v/ac4220863
A站所有视频都不能放

**Comment by esterTion** [comment]
试了下这个地址还是正常，迷幻
有chrome吗，有的话试一下chrome扩展正常不
不知道是服务器问题还是什么

**Comment by WangHongshuo** [comment]
装了chrome，试了一下插件，是正常的。

**Comment by WangHongshuo** [comment]
A站亡了 (

**Comment by esterTion** [comment]
![qq 20180202125611](https://user-images.githubusercontent.com/7265411/35717192-8ec0fd30-0818-11e8-9098-93aa8ee1b389.jpg)

**Comment by WangHongshuo** [comment]
A站复活了 上次404的问题也没有了
![img](http://imgsrc.baidu.com/forum/w%3D580/sign=3a89505c5a4e9258a63486e6ac83d1d1/c8cdadec08fa513d153dd4e6316d55fbb2fbd931.jpg)

**Comment by WangHongshuo** [comment]
控制台信息：
```
密码字段出现在一个不安全的 http:// 页面中。这是一个可能导致用户登录凭据被窃取的安全风险。
[详细了解]
ac4225200

指向“http://cdn.aixifan.com/acfun-pc/2.2.95/js/module/sensorsdata-event.min.js”的 <script> 加载失败。
ac4225200:24

Object { path: "http://cdn.aixifan.com/flash/player-view-homura.swf", version: "10.0.0", subPath: "false", width: 980, height: 568, flashvars: {…}, params: {…}, attributes: {…} }
detail.min.js:1:6396

指向“http://hm.baidu.com/hm.js?2af69bc2b378fb58ae04ed2a04257ed1”的 <script> 加载失败。
ac4225200:1

指向“http://cdn.aixifan.com/acfun-pc/2.2.95/js/lib/sensorsdata.1.3.4.min.js”的 <script> 加载失败。
ac4225200:1

Object { code: 200, data: {…}, message: "OK" }
detail.min.js:1:3833

来自一个外部异步载入的脚本的 document.write() 调用被忽略。
jia.js:1:19423

not implemented status 
Object { status: "202", msg: "{\"uid\":\"1357928\",\"uid_ck\":\"-979103340\",\"disabled\":\"false\",\"isAdmin\":\"false\",\"identified\":true,\"lv\":10,\"danmu_remaining_num\":-1,\"user_group_level\":1}" }
ABPlayer.min.js:formatted:2992

评论载入完成于470ms。
comm.min.js:2:19047

[AHP] Got sourceType: zhuzhan vid: 5a8157870cf2cf48678a0bfb
acfun_html5.js:481:21

运营位获取失败1518502241922
comm.min.js:2:20013

[AHP] Got source url 
Object { flvhd: {…}, duration: 1226000, mp4hd: {…}, mp4hd2: {…} }
acfun_html5.js:171:9

[IOController] > Loader error, code = 403, msg = Forbidden
flv.min.js:1:4369

[TransmuxingController] > IOException: type = HttpStatusCodeInvalid, code = 403, msg = Forbidden
flv.min.js:1:4369

源映射错误：TypeError: NetworkError when attempting to fetch resource.
源 URL：moz-extension://31e5e920-16fe-4606-9dfe-e157df3f972d/flv.min.js
源映射 URL：flv.min.js.map
[详细了解]

[comm.readyEditor()]编辑器加载完成。
comm.min.js:2:8663

Error: Permission denied to access property "type"
[详细了解]
```

**Comment by esterTion** [comment]
又来了？
所以说我这边无法复现啊，都不知道怎么解决

**Comment by WangHongshuo** [comment]
看到了个这个：
```
源映射错误：TypeError: NetworkError when attempting to fetch resource.
源 URL：moz-extension://31e5e920-16fe-4606-9dfe-e157df3f972d/flv.min.js
源映射 URL：flv.min.js.map
[详细了解]
```

**Comment by esterTion** [comment]
这个是正常的，调试用的映射map我没打包，就找不到了

**Comment by WangHongshuo** [comment]
呜呜呜 (
没接触过前端和js，问题除了弹出来的403以外，真的是没有任何可以描述的了，好难过啊。
不过`flv.min.js`是做过混淆吗，读起来真的是 (
提前祝大佬情人节快乐  ）

**Comment by esterTion** [comment]
`.min.js`都是混淆，处理器会进行优化的，执行起来效率会比原始代码高些

情人节什么的不存在的

**Comment by WangHongshuo** [comment]
![img](http://cdn.aixifan.com/dotnet/20130418/umeditor/dialogs/emotion/images/ac3/10.gif)新年快乐~

**Comment by esterTion** [comment]
新年快乐~

**Comment by WangHongshuo** [comment]
最近试了下家里的电脑 win10 64位 版本 10.0.16299.214 firefox  58.0.1 64位 只装AcFun-HTML5-Player还是提示403 (

DNS:202.102.152.3 和 202.102.154.3 是A站姨妈了吗 (

**Comment by esterTion** [comment]
给你说点问题细节吧
a站视频要么用手机ua，要么带上来源
chrome扩展请求可以设置带来源
火狐不带，然后ua的话本来57之后应该可以修改了，但你这个大概是没改成，原因我也不知道，说不定是某个设置项导致的

排错的话进到`%appdata%\Mozilla\Firefox\Profiles`下，把那个xxxx.default目录备份一下然后清掉（default目录本身别删），开开重装扩展看看好没
我现在不知道怎么修，你这样排查一下好了就是某个设置的问题，没好就gg

**Comment by WangHongshuo** [comment]
我油猴脚本里有转html5的脚本，但是只是将A站视频网址转换成html5网址，相当于打开手机网页，这个应该是影响不到的。
我尝试的操作是这样的：

1. 保存xxxx.default配置文件目录，把firefox卸载全部清理掉（包括Local, LocalLow, Roming三个文件夹下的文件），重新安装firefox（用此方法尝试了52， 56， 57， 57.0.1， 58， 58.0.2， 59beta9几个版本），不登录账号同步，不安装任何插件，不恢复配置文件，只安装AcFun-HTML5-Player，都是显示403，很难受，感觉自己是被A站ban了  (

2. 通过把firefox卸载并全部清理掉（包括Local, LocalLow, Roming三个文件夹下的文件），重新安装58.0.2版本，不从本地恢复配置文件，从云端同步各种配置后可以用了(黑人问号.jpg)，非常不明白为什么，之前一直以为是A站的锅，把我屏蔽了,因为提示403 (

我感觉~如果让我找锅的话~，可能是：

1. 火狐更新过程中，出现配置文件不匹配问题，或者是自己在卸载和清理firefox时，并没有做干净(真想不出还有哪里残留了）。

2. 火狐更新过程中，某个插件与其不匹配，但作者没有更新(好像有些插件权限蛮大的)，我插件里有个[斗鱼HTML5播放器](https://addons.mozilla.org/zh-CN/firefox/addon/douyuhtml5player/?src=api)，也是基于flv.js的，很可能是这个有问题，因为其他的插件真的是想不出来能影响AcFun-HTML5-Player。

~其实我也蛮担心是不是A站在我尝试的时候暂时放我出来了~
- [x] 又可以愉快的逛缺逼乐了，给大佬添麻烦了，可以添加solved了  ）

**Comment by esterTion** [comment]
过于奇幻，理解不能（

**Comment by WangHongshuo** [comment]
老哥，回学校后翻新了一下浏览器，插件又可以用了，不错这次抓到一个新的错误。

> 播放错误
{
  "type": "MediaError",
  "info": "MediaMSEError",
  "detail": {
    "code": 11,
    "msg": "An attempt was made to use an object that is not, or is no longer, usable"
  }
}

附视频页：[http://www.acfun.cn/v/ac4217478](http://www.acfun.cn/v/ac4217478)

**Comment by esterTion** [comment]
神tm 96kHz的音频
火狐播不了，chrome可以
视频问题

**Comment by esterTion** [comment]
完美
我前几天升级55到59了，然后我也碰到这个鬼问题了（笑到豹毙.jpg）
所以应该还是某个设置的问题，是啥我就不知道了，我再研究研究

**Comment by WangHongshuo** [comment]
我目前还没有出现这个问题，不知道是不是网络层面的原因，因为从家里滚回来了 (
我以前怀疑是[斗鱼HTML5播放器 ](https://addons.mozilla.org/zh-CN/firefox/addon/douyuhtml5player/)的问题，因为都是基于flv.js，可能在某个层面上会劫持一下造成错误解析？
我浏览器翻新后就再也没装过这个斗鱼HTML5播放器插件了，现在正常用了一个月了。
我现在的插件有：

1. [smartup手势](https://addons.mozilla.org/zh-CN/firefox/addon/smartup/)
2. [Tab Suspender (memory saver)](https://addons.mozilla.org/zh-CN/firefox/addon/tab-suspender-tab-unloader/)
3. [Tampermonkey](https://addons.mozilla.org/zh-CN/firefox/addon/tampermonkey/)
4. [ThunderCross](https://addons.mozilla.org/zh-CN/firefox/addon/thundercross/)
5. [uBlock Origin](https://addons.mozilla.org/zh-CN/firefox/addon/ublock-origin/)
6. [Undo Closed Tabs Button](https://addons.mozilla.org/zh-CN/firefox/addon/undo-closed-tabs-revived/)
7. [Zoom Page WE](https://addons.mozilla.org/zh-CN/firefox/addon/zoom-page-we/)

**Comment by esterTion** [comment]
草，笑死
flash都被403可还行，看来是垃圾cdn石锤了
![qq 20180321124255](https://user-images.githubusercontent.com/7265411/37694859-66d5638a-2d05-11e8-8402-bf556fc075df.png)
