### ISSUE TITLE
弹幕列表为空

### ISSUE THREAD

**Issue by PrOmPt0** [esterTion/AcFun-HTML5-Player#14]
![image](https://user-images.githubusercontent.com/18552607/36150168-c0699b56-10fd-11e8-8153-29dd9a3638f3.png)

貌似原来flash播放器是加载播放器后才请求弹幕列表

**Comment by esterTion** [comment]
地址

**Comment by PrOmPt0** [comment]
@esterTion http://www.acfun.cn/v/ac4225257
![image](https://user-images.githubusercontent.com/18552607/36183058-93610936-1167-11e8-8a64-2dc49cd8cb1b.png)
HTML5
![image](https://user-images.githubusercontent.com/18552607/36183122-d37d95a2-1167-11e8-9667-e25c1b8a1ded.png)
Flash

**Comment by PrOmPt0** [comment]
![image](https://user-images.githubusercontent.com/18552607/36184271-a702589a-116d-11e8-8291-55851810f08e.png)
版本 66.0.3346.0（正式版本）canary （64 位）
![image](https://user-images.githubusercontent.com/18552607/36184298-c9dc0352-116d-11e8-916c-0fd39e819908.png)
版本 66.0.3343.3（正式版本）dev （64 位）

其他扩展都禁用了不行，奇怪了
大概是我自己的问题，dalao打扰了
@esterTion

**Comment by esterTion** [comment]
按你这个截图的话，是chrome开发版的bug
