### ISSUE TITLE
弹幕池过多存在延迟卡顿现象

### ISSUE THREAD

**Issue by jonah-tao** [esterTion/AcFun-HTML5-Player#15]
最近在看[爆刘继芬](http://www.acfun.cn/v/ac213736) 时,发现弹幕池过多后出现了很明显的延迟卡顿现象,切换回flash播放器后状况好转点.

机器是
i7-4760HQ 
HD5200
12GRAM 
120GSSD 
MacOS10.13.2 
Chrome(x64)  63.0.3239.132

**Comment by esterTion** [comment]
看了一下，flash只加载1.2w，对播放器是瞎扯的

**Comment by jonah-tao** [comment]
... 这个是否可以成为一个feature呢?

**Comment by esterTion** [comment]
我昨天更新了也限制加载12页
（现在想想突然意识到可能是10页，因为还有高级弹幕）

**Comment by jonah-tao** [comment]
好的,我关闭issue了,多谢作者了
