### ISSUE TITLE
opensuse不能播放。

### ISSUE THREAD

**Issue by Nojike** [esterTion/AcFun-HTML5-Player#16]
這個是提示。
  "type": "MediaError",
  "info": "MediaMSEError",
  "detail": {
    "code": 9,
    "msg": "Operation is not supported"
  }
}

**Comment by esterTion** [comment]
视频地址

**Comment by Nojike** [comment]
是A站所有视频都看不了，系统是opensuse 浏览器是火狐。我就是装系统来玩玩的，不用麻烦了。。。
