### ISSUE TITLE
白屏问题

### ISSUE THREAD

**Issue by maltose1993** [esterTion/AcFun-HTML5-Player#17]
下滚网页之后再返回视频会变成白屏

**Comment by esterTion** [comment]
emmm
我第一遍打开一个出现了，然后刷新准备研究的时候没了，然后就再没出现过……

**Comment by maltose1993** [comment]
= =任何视频我都遇到

**Comment by maltose1993** [comment]
@esterTion 找到白屏原因了 播放器看一下评论 播放器就飘到右边去了
![q 6 6rrzd 4hmfcwi jn0u4](https://user-images.githubusercontent.com/15636473/37475407-9ff68c9a-28ad-11e8-8b87-ad238c602622.png)

**Comment by jonah-tao** [comment]
同样遇到了这种情况
macos10.13.3
chrome65.0.3325.162
播放器主题bilibili和youtube都存在这个问题

复现步骤(非全屏/铺满屏幕观测明显)
1. 打开任何视频比如 http://www.acfun.cn/v/ac4272262
2. 替换播放器完成
3. 滚轮滑动到下方播放器切换mini模式(未看到mini模式的界面)
4. 滚轮滑动到播放器位置时 播放器向右偏离了位置
