### ISSUE TITLE
收藏夹里找到的tudou源视频，不知道还有没有希望

### ISSUE THREAD

**Issue by ricekiller** [esterTion/AcFun-HTML5-Player#2]
http://www.acfun.cn/v/ac907019
印象中非常低俗的一首歌，弹幕还不少。
至于收藏夹里其它视频除了爆破的都还能看。
顺便祭奠一下乐视。

**Comment by esterTion** [comment]
tudou源我印象中会有来源限制
外链过多会导致域名被黑名单，但没有来源直接拒绝
我之后看看

**Comment by esterTion** [comment]
我看了下，土豆旧视频id系统所有接口都没了
应该是所有视频都转到了优酷id下，但是没有地方能找到对应id
连官方都没写这个功能，所以flash会直接卡住，因为没有id

**Comment by esterTion** [comment]
又找了找，ac存了原始地址，里面有vcode `NpXjHhAbDAQ`  
但是用旧链接也获取不到跳转，很大可能是被删除了  
http://www.tudou.com/programs/view/html5embed.action?code=NpXjHhAbDAQ  
有没有其他的土豆源视频？

**Comment by esterTion** [comment]
企鹅源更绝望（
至今没有什么好的获取路子，那套加密死复杂
看来只剩新源可以看了（

**Comment by ricekiller** [comment]
@esterTion 企鹅源我从网上看了看，凉了凉了真凉了。
另外土豆视频我又从主站上搜了一下，（就是搜tudou.com，看简介里有没有源地址，辣鸡搜索我都不想吐槽），找到两个例子。
http://www.acfun.cn/v/ac2567429 对应
http://video.tudou.com/v/XMjQzNjc3MjU0OA==.html
http://www.acfun.cn/v/ac2427670 对应
http://video.tudou.com/v/XMjQyODQxMDk4MA==.html
其实这个问题放着也可以，反正现在土豆源的视频也没有什么需要值得补档的...
我估计应该是和新浪一样，只能修复部分视频，很多源应该都被清理了...

**Comment by esterTion** [comment]
新浪其实还好，我倒是觉得比较奇怪，因为b站那边大部分番剧新浪都是没问题的状态，我最开始做适配的时候找了几个老视频结果全是隐藏还惊到我了

另外我问了个比较了解的人，土豆所有旧视频，过审的都存优酷了，获取方法就是那种看跳转。没过审的全没了（其实本来没过审就应该消失才对）

**Comment by BDPO** [comment]
虽然已经毫无希望了，我还是写一下吧【土豆源相关】

这是旧的UP投稿管理界面，可能有用，[请看图片](http://imgs.aixifan.com/o_1c1l02t8g23n115mkr41bsj1qdb7.png)
以下分P，vid参数你懂的

http://www.acfun.cn/v/ac2665790_1 vid=3391710
能播放的土豆链接http://video.tudou.com/v/XMjA0NjI5MzI2NA==.html

http://www.acfun.cn/v/ac2665790_2 vid=3391715
能播放的土豆链接http://video.tudou.com/v/XMjA0NjI5MzMzMg==.html

**Comment by esterTion** [comment]
vid没用，sid有用
过审视频可以获取跳转地址，取出来X开头的id就是优酷源了

**Comment by BDPO** [comment]
我给的这个vid，可以通过某些半公开API查到你需要的sid/vcode，[详见](https://github.com/zhihaofans/Acfun/blob/master/acfun.tv/The-api-for-acfun/api.md)

### 获取视频信息
    主域名/video/getVideo.aspx?id=(分P视频 vid)

### 检测视频是否存在
    /video/checkVideo.aspx?id=(vid)
