### ISSUE TITLE
为啥这几天只能加载一半

### ISSUE THREAD

**Issue by gcxgood** [esterTion/AcFun-HTML5-Player#20]
不知是否我的问题，外站源的视频只能加载一半
http://www.acfun.cn/bangumi/ab5020161_29280_234800
http://www.acfun.cn/bangumi/ab5021446_30614_266397
等等~

**Comment by esterTion** [comment]
优酷有地址失效重新载入的，控制台内容复制一下？

**Comment by gcxgood** [comment]
bangumi.min.js:1 Object {path: "http://cdn.aixifan.com/player/cooperation/AcFunXYouku.swf?v=2.3.01", version: "10.0.0", subPath: "false", width: 1160, height: 568…}
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/member/getUserGroupLevel.aspx".
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
checkAndPullGroupLevel @ main.min.js:1
init @ main.min.js:1
(anonymous) @ main.min.js:2
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/member/unRead.aspx?uid=661672".
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
getUnRead @ main.min.js:1
(anonymous) @ main.min.js:2
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/album/abm/bangumis/video?albumId=5020161&groupId=29280&num=1&size=50&_=1521285790369".
send @ library.min.js:3
ajax @ library.min.js:3
B @ bangumi.min.js:1
(anonymous) @ bangumi.min.js:1
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/comment/comment_count.aspx?contentId=5020161&type=ab".
send @ library.min.js:3
ajax @ library.min.js:3
ue @ bangumi.min.js:1
(anonymous) @ bangumi.min.js:1
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://tongji.aixifan.com:8106/sa.gif?uuid=e597db3e3fd0538fe767bd85a8559bee".
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
(anonymous) @ main.min.js:1
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/online.aspx?uid=661672".
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
(anonymous) @ comm.min.js:2
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/special_view.aspx?specialId=5020161".
send @ library.min.js:3
ajax @ library.min.js:3
fe @ bangumi.min.js:1
(anonymous) @ bangumi.min.js:1
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/album/abm/bangumis/iscollect?albumId=5020161".
send @ library.min.js:3
ajax @ library.min.js:3
he @ bangumi.min.js:1
(anonymous) @ bangumi.min.js:1
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/api/friend.aspx?name=checkFollow&userId=-1".
send @ library.min.js:3
ajax @ library.min.js:3
ve @ bangumi.min.js:1
(anonymous) @ bangumi.min.js:1
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/online.aspx".
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
(anonymous) @ bangumi.min.js:1
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/member/getUserGroupLevel.aspx".
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
(anonymous) @ comm.min.js:2
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
sensorsdata.1.3.4.min.js:1 Object {distinct_id: "159f04df9c0470-050625222bf3ba-17187357-1fa400-159f04df9c1359", properties: Object, type: "profile_set_once", time: 1521285790944}
VM1914:1 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
(anonymous) @ VM1914:1
(anonymous) @ VM1914:1
(anonymous) @ jia.js?uid=2106688&_=1521285790370:2
acfun_html5.js:464 Fetch complete: GET "http://www.acfun.cn/video/getVideo.aspx?id=5715937".
playerIframe.onload @ acfun_html5.js:464
acfun_html5.js:481 [AHP] Got sourceType: youku vid: XMTUyMTM2MjU4OA==
acfun_html5.js:471 Fetch complete: GET "http://danmu.aixifan.com/size/5715937".
(anonymous) @ acfun_html5.js:471
ABPlayer.min.js:3 not implemented status Object {status: "202", msg: "{"uid":"661672","uid_ck":"-2056739797","disabled":…19,"danmu_remaining_num":-1,"user_group_level":1}"}
acfun_html5.js:370 Fetch complete: GET "http://danmu.aixifan.com/V2/5715937?pageSize=1000&pageNo=1".
loadCommentBySize @ acfun_html5.js:370
acfun_html5.js:575 Fetch complete: GET "https://player.youku.com/player.php/sid/XMTUyMTM2MjU4OA==/newPlayer/true/v.swf".
sourceTypeRoute @ acfun_html5.js:575
(anonymous) @ acfun_html5.js:489
acfun_html5.js:585 Fetch complete: GET "https://api.youku.com/players/custom.json?client_id=0edbfd2e4fc91b72&video_…4fc6a86c4c15234d2ae1905446d8&embsig=undefined&styleid=undefined&type=flash".
(anonymous) @ acfun_html5.js:585
acfun_html5.js:593 Fetch complete: GET "https://ups.youku.com/ups/get.json?vid=XMTUyMTM2MjU4OA==&ccode=0405&client_…qK7&client_ts=1521285791716&r=TJXNtWdcb6ky/owezfVSuXnpukKzi7vM0BjPLATFP6U=".
(anonymous) @ acfun_html5.js:593
acfun_html5.js:171 [AHP] Got source url Object {flvhd: Object, duration: 600000, mp4hd: Object, mp4hd2: Object}
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/comment/bangumi/web/list?isNeedAllCount=true&bangumiId=5020161&pageNo=1".
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
showComm @ comm.min.js:2
(anonymous) @ comm.min.js:2
r @ library.min.js:2
dispatch @ library.min.js:2
g.handle @ library.min.js:2
trigger @ library.min.js:2
(anonymous) @ library.min.js:2
each @ library.min.js:1
each @ library.min.js:1
trigger @ library.min.js:2
ie.fn.(anonymous function) @ library.min.js:3
ready @ comm.min.js:2
e @ comm.min.js:2
window.comment @ comm.min.js:2
(anonymous) @ bangumi.min.js:1
comm.min.js:2 评论载入完成于1339ms。
comm.min.js:2 [comm.readyEditor()]编辑器加载完成。
library.min.js:3 XHR finished loading: GET "http://www.acfun.cn/appspreadcontents/ad?type=comm1".
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
(anonymous) @ comm.min.js:2
c @ library.min.js:2
fireWith @ library.min.js:2
n @ library.min.js:3
t @ library.min.js:3
flv.min.js:1 Fetch complete: GET "http://222.216.189.206/6977374056C4A83FA4D4E52450/030001080057000826A78B146…MjU4OA%3D%3D&vkey=A2375432eb05018b8592bd3890b72eed5&s=af361582e59c11e5b32f".
open @ flv.min.js:1
_internalSeek @ flv.min.js:1
seek @ flv.min.js:1
seek @ flv.min.js:1
seek @ flv.min.js:1
_checkAndApplyUnbufferedSeekpoint @ flv.min.js:1




额。。。这样么？并不太懂

**Comment by jonah-tao** [comment]
在A站查看返回信息的时候看到的是时间

**Comment by jonah-tao** [comment]
在A站查看返回信息的时候看到的是时间是对的,但是播放器给(优酷外链播放器 和acfun html player)的时间错误了
![image](https://user-images.githubusercontent.com/10397378/37818345-cd8bad2c-2eb4-11e8-810a-be04bd46c0ff.png)

![image](https://user-images.githubusercontent.com/10397378/37818250-7f54961e-2eb4-11e8-8943-47055372d811.png)

**Comment by esterTion** [comment]
哦我懂了，版权投稿限制了外链了，只给看10min
我走的是acfun外链同一个路子所以都是被限制，他那个ckey算起来还挺操蛋我没去研究过

**Comment by gcxgood** [comment]
其实可以加载到十几分钟，到10分钟后会继续加载，但是之后就真的卡住了

**Comment by esterTion** [comment]
因为分段不是整十分钟，播完那个分段就没了
我按照you-get的路径试一下能不能用

**Comment by esterTion** [comment]
更新了1.2.0，加载了一个优酷主站的子页面代获取地址
可能有提前发出声音的副作用，并且页面会变得极卡无比（因为yk的前端代码太tm垃圾了）
