### ISSUE TITLE
在FF应用市场上下架了？

### ISSUE THREAD

**Issue by pgain2004** [esterTion/AcFun-HTML5-Player#22]
如题：https://addons.mozilla.org/en-US/firefox/addon/acfun-html5-player-estertion/

**Comment by esterTion** [comment]
是被下了
审核很烦一直要提供源码，懒得弄就被停了。而且很久之前就那一个人一直特别烦人，其他审核都不太管的
换首页的自分发安装吧，扩展里保存的设置不是很多
