### ISSUE TITLE
下滑页面会导致播放器的消失

### ISSUE THREAD

**Issue by zhang1813023404** [esterTion/AcFun-HTML5-Player#24]
你好啊亲爱的作者同♂志。

在我的浏览器里有这个问题，我不确定是否是我运行环境的问题，所以我认为我需要在最后贴出环境信息。

我在普通**未播放模式**下，将页面下滑到评论位置，再滑上来后发现本该是播放器的位置没有了播放器，取而代之的是空白。

而在**播放模式**下，重复上滑下滑动作，播放器将被**右移**。

系统环境：Ubuntu17.10 64bit ~~~（去wmi驱动）~~~
硬件环境：某知名厂商的笔记本
浏览器环境： Chrome 65.0.3325.181(正式版) （64位）
播放器版本：v1.1.1(HTML5 Player ver.171228 based on ABPlayer-bilibili-ver)

**Comment by zhang1813023404** [comment]
抱歉没看到之前的问题 #17

**Comment by esterTion** [comment]
新版我修了啊……

**Comment by zhang1813023404** [comment]
@esterTion 找到原因了，我完全卸载播放器又重新下载安装后就正确了，可能之前下载的是老版本……吧……
