### ISSUE TITLE
请也支持爱稀饭的

### ISSUE THREAD

**Issue by noahhhi** [esterTion/AcFun-HTML5-Player#25]
http://www.aixifan.com/ 并不会一并转换.

**Comment by BDPO** [comment]
**我觉得支持列表不包含爱稀饭比较好**

因为有可能，部分高级弹幕视频，需要使用flash播放器看，才能达到比较好的效果。你可以对比一下例如：
http://www.acfun.cn/v/ac314065 [对应的爱稀饭地址](http://www.aixifan.com/v/ac314065)
默认使用作者的[ABPH5](https://github.com/esterTion/AcFun-HTML5-Player)，弹幕核心是[CCL](https://github.com/esterTion/AcFun-HTML5-Player/issues/3#issuecomment-352455419)
关于CCL，具体请参考KNH的 [博客](https://kanoha.org/2012/03/22/abplayerhtml5-commentcorelibrary-and-more/)和[github](https://github.com/jabbany/CommentCoreLibrary)

CCL确实支持了一部分高级弹幕，但有些古老的高级弹幕，还请使用flash播放器观看，以获得更好的弹幕观感体验，比如
http://www.aixifan.com/v/ac314065 （绯色月下）
http://www.aixifan.com/v/ac1282697
http://www.aixifan.com/v/ac1758344
http://www.aixifan.com/v/ac1766872

写这么多并不是说ABPH5和CCL不好，相反，我很感谢各位作者的辛勤努力！

我主观认为，留个爱稀饭地址，不加入ABPH5的转换，在某些需要flash播放器的场合下，可以救急（比如上面提到的部分高级弹幕）

当然，既然PO主提出了这个需求，我可以献计一条
参考我以前摸鱼的[ACU](https://github.com/BDPO/Auto-Change-URL/blob/master/acu-v2.js#L12)，魔改一下，得到如下代码
就是把网址由www.aixifan.com跳转到http://www.acfun.cn/ 从而使得ABPH5识别域名，曲线救国嘛
##### 
    javascript:(function(){window.location.href = window.location.href.replace(/^http:\/\/www.\aixifan\.com\//, 'http:\/\/www.\acfun\.cn\/');})();

请复制以上完整代码，加入收藏夹，在需要从爱稀饭域名跳转到acfun的时候，点击一下

**Comment by esterTion** [comment]
谢谢你的回复让我想起了这个反馈（我那天要看的然后忘了😂）

这个提议也不错，留一个flash的入口，所以我可以考虑加个跳转设置
或者干脆就不加了（毕竟我懒，虽然都自动化更新了）
