### ISSUE TITLE
又是和上次类似的问题

### ISSUE THREAD

**Issue by gcxgood** [esterTion/AcFun-HTML5-Player#28]

**Comment by gcxgood** [comment]
回车就发出去了。。。
进度条加载不完整，上次是优酷外链
这次是主站的视频了，是我的问题还是啥呢

detail.min.js:1 {path: "http://cdn.aixifan.com/flash/player-view-homura.swf", version: "10.0.0", subPath: "false", width: 1160, height: 568, …}
sensorsdata.1.3.4.min.js:1 {distinct_id: "162c387a423474-0d769d5a5ef32c-4446062d-1fa400-162c387a424982", properties: {…}, type: "profile_set_once", time: 1530075576012}
sensorsdata.1.3.4.min.js:1 {distinct_id: "162c387a423474-0d769d5a5ef32c-4446062d-1fa400-162c387a424982", properties: {…}, type: "track", event: "Detailpage", time: 1530075576013}
detail.min.js:1 {code: 200, data: {…}, message: "OK"}
ac4427396:1 Cross-origin plugin content from http://cdn.aixifan.com/acfun-pc/2.3.63/flash/ZeroClipboard.swf?noCache=1530075575850 must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.
ac4427396:1 Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.
acfun_html5.js:488 [AHP] Got sourceType: zhuzhan vid: 5b304d060cf2636294951bcb
ABPlayer.min.js:3 not implemented status {status: "202", msg: "{"uid":"661672","uid_ck":"-2056739797","disabled":…20,"danmu_remaining_num":-1,"user_group_level":1}"}
comm.min.js:2 评论载入完成于139ms。
acfun_html5.js:178 [AHP] Got source url {flvhd: {…}, duration: 733000, mp4hd: {…}, mp4hd2: {…}}
library.min.js:3 GET http://www.acfun.cn/appspreadcontents/ad?type=comm1 500 (Internal Server Error)
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
(anonymous) @ comm.min.js:2
c @ library.min.js:2
fireWith @ library.min.js:2
n @ library.min.js:3
t @ library.min.js:3
XMLHttpRequest.send (async)
send @ library.min.js:3
ajax @ library.min.js:3
ie.(anonymous function) @ library.min.js:3
showComm @ comm.min.js:2
(anonymous) @ comm.min.js:2
r @ library.min.js:2
dispatch @ library.min.js:2
g.handle @ library.min.js:2
trigger @ library.min.js:2
(anonymous) @ library.min.js:2
each @ library.min.js:1
each @ library.min.js:1
trigger @ library.min.js:2
ie.fn.(anonymous function) @ library.min.js:3
ready @ comm.min.js:2
e @ comm.min.js:2
window.comment @ comm.min.js:2
(anonymous) @ detail.min.js:1
setTimeout (async)
(anonymous) @ detail.min.js:1
c @ library.min.js:2
fireWith @ library.min.js:2
ready @ library.min.js:2
s @ library.min.js:1
comm.min.js:2 运营位获取失败1530075576632
comm.min.js:2 [comm.readyEditor()]编辑器加载完成。

**Comment by gcxgood** [comment]
ac4427396

**Comment by esterTion** [comment]
怎么个不完整法

**Comment by gcxgood** [comment]
好比视频有20分钟，只能加载出10分钟，放到10分钟位置又加载1分钟然后就再不加载了

**Comment by esterTion** [comment]
这视频就12min啊，哪来20分钟

优酷那个是版权外链限制，我已经加了绕路应该也没了

**Comment by Sun-FreePort** [comment]
@gcxgood 我这边正常的播放完了。
中间的确缓冲了一会儿，或许是部分视频地址的下载速度慢吧，但没有出现不再加载的情况。

@esterTion 提问者说的是「好比」，冷静啊朋友。
