### ISSUE TITLE
影视区重开，该版块下的视频地址改变，插件暂时不能用

### ISSUE THREAD

**Issue by ricekiller** [esterTion/AcFun-HTML5-Player#3]
影视区地址：http://www.acfun.cn/v/list68/index.htm
除了国外电影其它都还在，包括纪录片形式的电影。
看了看我之前的投稿，影视区开了后符合要求的又过了，国外电影估计是不行了。不过有日综看就很满足了。
另外影视区下的视频跳转到新的地址，比如：http://v.hapame.com/video/id4138045
没记错的话应该是原来孙总的网站，这个网站有视听许可证。
除了地址不同其它应该都有保留，包括弹幕和评论，视频源不知道。
H5播放器应该能适配到新的页面吧。
PS:这个问题和先前的不是同一类，所以就新开issue了|∀` )

**Comment by esterTion** [comment]
emmm，这个地址
只有这一个域名的话我就加进去匹配就行了
还有没有其他的

**Comment by esterTion** [comment]
更新了
因为我懒的原因，弹幕屏蔽列表/视频播放位置是localStorage，不能跨域名同步，播放器主体设置是扩展存储
就这样

**Comment by ricekiller** [comment]
域名暂时没有其它的了，播放器我感觉已经做的非常好了，用户体验比之前提高了N个层次。
如果还问有没有问题的话，我只能吹毛求疵的说一些，因为无伤大雅，所以无论最终有没有处理都没有意见。
高级弹幕不能显示，因为不懂原理，所以不知道其中的难度，比如http://www.acfun.cn/v/ac1282697_1，不过目前也很少有人做高级弹幕了...
弹幕池是不是只能按照发送时间进行排序，我想按照视频时间排序发现无效。
在评论区时，小的播放器框会受到方向键的影响，比如我在进行评论时，如果想用方向键移动光标到别的文字位置不会起作用，反而会使视频进度改变（除了输入文字时在拼音框使用方向键不会影响进度条）。如果不使用插件，原来的播放器则是正常的。
嗯，暂时这些...最近也要忙硕士论文，所以可能回应不及时请见谅。

**Comment by esterTion** [comment]
排序按理可以，回头看看
打字时方向键也[不应该被识别](https://github.com/esterTion/AcFun-HTML5-Player/blob/master/src/acfun_html5.js#L747)，设计input/textarea不转发键盘事件的

**Comment by BDPO** [comment]
AC高级弹幕在HTML5上确实很难做到显示，具体原理过于复杂。
不过我可以提供一个范例，请看http://www.acfun.cn/v/ac3025209

就拿Part 1来说，此分P vid=4444400
调用某半公开API查到[弹幕池](http://danmu.aixifan.com/V2/4444400)
看似内容杂乱无章，实际可以分段解析

第一部分，普通弹幕（滚动，顶端，底部）
http://danmu.aixifan.com/V3/4444400_2/1/500

第二部分，高级弹幕
http://danmu.aixifan.com/V3/4444400_1/1/500
其中高级弹幕遵循

**Comment by esterTion** [comment]
其实CCL有acfun解析器
你不提我都忘了，因为一直只接触b站弹幕所以早都把a站解析器删了，然后迁移youku把b站解析器也删了

**Comment by BDPO** [comment]
**之前删掉的内容：**

AC高级弹幕在HTML5上确实很难做到显示，具体原理过于复杂。
不过我可以提供一个范例，请看http://www.acfun.cn/v/ac3025209
就拿Part 1来说，此分P vid=4444400

调用某半公开API查到[弹幕池](http://danmu.aixifan.com/V2/4444400)
看似内容杂乱无章，实际可以分段解析

第一部分，普通弹幕（滚动，顶端，底部）
http://danmu.aixifan.com/V3/4444400_2/1/500
第二部分，高级弹幕
http://danmu.aixifan.com/V3/4444400_1/1/500

另外你可参考
https://boomfun.work/tool/5 https://boomfun.work/tool/10
两插件对高弹的判定和显示，虽然不一定最好，但可能会帮到你

**Comment by esterTion** [comment]
我看到这个了，发出来的时候可是会有邮件的（

**Comment by haocity** [comment]
...ccl是什么？求科普。。。

**Comment by BDPO** [comment]
Re: @haocity 其实我也不懂...
你可参考KNH的 [博客](https://kanoha.org/2012/03/22/abplayerhtml5-commentcorelibrary-and-more/)和[github](https://github.com/jabbany/CommentCoreLibrary)

**Comment by haocity** [comment]
Thank,等我后天考试后好好看看
