### ISSUE TITLE
403错误

### ISSUE THREAD

**Issue by WangHongshuo** [esterTion/AcFun-HTML5-Player#30]
> { "type": "NetworkError", 
> "info": "HttpStatusCodeInvalid", 
> "detail": { "code": 403, "msg": "Forbidden" } }

对唔住带哥，又是上次的问题，一回到家就出现这种问题了，要不有时间来我这抓个log  ）

**Comment by esterTion** [comment]
emmm，又来了么
应该还是网络的问题
用的是chrome吗？F12看Network里面`video.acfun.tv`是什么情况

**Comment by esterTion** [comment]
firefox确实看不到
尝试用chrome装crx再看看吧，firefox的插件调试烂的不行，我虽然日常用ff但是开发必须要用ch
