### ISSUE TITLE
src里面的dom_gen.js似乎和安装的压缩包里面内容有点不同

### ISSUE THREAD

**Issue by zwjhuhu** [esterTion/AcFun-HTML5-Player#32]
[src/dom_gen.js](https://github.com/esterTion/AcFun-HTML5-Player/blob/master/src/dom_gen.js)

大概是这附近吧
```
    if (children) {
        for (let i = 0; i < children.length; i++) {
            if (children[i] != null)
                elem.appendChild(children[i]);
        }
    }
```

具体没有仔细看我直接加载了下src文件夹，运行了下发现报错了

**Comment by esterTion** [comment]
还真是，1.2.3改了忘了复制过去（开发和git不是一个目录）
![qq 20181005093356](https://user-images.githubusercontent.com/7265411/46511565-eac64980-c881-11e8-87ca-179f477b1302.png)
直接加载src是会报错，因为manifest里面加载的都是.min.js，需要压缩
（我才发现ac播放器没扔那个脚本，懒得同步了可以大概参考下 [Youku/!compress.js](https://github.com/esterTion/Youku-HTML5-Player/blob/master/src/!compress.js) 和 [Youku/yhp_update](https://github.com/esterTion/Youku-HTML5-Player/blob/master/src/yhp_update)

**Comment by zwjhuhu** [comment]
哦，原来是这样的么，manifest里面一开始加载的时候就会说找不到文件，我马上改了下就忘记了。生成dom的那个小问题我估计也是哪里没同步而已。

感谢回复。
