### ISSUE TITLE
频繁502，无法播放

### ISSUE THREAD

**Issue by sirenfrappe** [esterTion/AcFun-HTML5-Player#33]
播放错误

{
  "type": "NetworkError",
  "info": "HttpStatusCodeInvalid",
  "detail": {
    "code": 502,
    "msg": "No data received from server or forwarder"
  }
}

播放错误

{
  "type": "NetworkError",
  "info": "Exception",
  "detail": {
    "code": -1,
    "msg": "Failed to fetch"
  }
}

**Comment by esterTion** [comment]
推测网络问题，flash能不能看

**Comment by sirenfrappe** [comment]
flash也经常播放失败，应该是又大姨妈了
