### ISSUE TITLE
403错误

### ISSUE THREAD

**Issue by Chunbear** [esterTion/AcFun-HTML5-Player#35]
播放错误

{
  "type": "NetworkError",
  "info": "HttpStatusCodeInvalid",
  "detail": {
    "code": 403,
    "msg": "Forbidden"
  }
}
昨天就这样了，今天还是没有改观。
Chrome 版本 68.0.3440.106（正式版本） （64 位）

**Comment by esterTion** [comment]
我这没问题……

点开f12点到Network，搜索·video.acfun.cn·然后刷新，把看到的403的请求右键`Copy > Copy link address`和`Copy > Copy request headers`和`Copy > Copy response headers`一起复制过来扔这我看下
**注意把request headers底下的Cookie删除掉，这个是你的登录信息**

**Comment by Chunbear** [comment]
[Copy link address ]:
http://117.131.216.198:6510/video.acfun.cn/010040020400005BC4BD6A00010000BB0000000000-0000-0000-022E-F46700000000.mp4?customer_id=5859fdaee4b0eaf5dd325b91&auth_key=1539673028-101042431628103421d852c6f1d7d453cc65fb27cc9erpcx12111p30p231p11357cd72c29279-ACFUN-0c1549e9c59bb2f58d5ecf1895cf9f7c

[Copy request headers ]:
GET /video.acfun.cn/010040020400005BC4BD6A00010000BB0000000000-0000-0000-022E-F46700000000.mp4?customer_id=5859fdaee4b0eaf5dd325b91&auth_key=1539673028-101042431628103421d852c6f1d7d453cc65fb27cc9erpcx12111p30p231p11357cd72c29279-ACFUN-0c1549e9c59bb2f58d5ecf1895cf9f7c HTTP/1.1
Host: 117.131.216.198:6510
Connection: keep-alive
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Accept: */*
Referer: http://www.acfun.cn/v/ac4645655
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9

 [Copy response headers :]
HTTP/1.1 403 Forbidden
Date: Tue, 16 Oct 2018 04:27:08 GMT
Content-Type: video/mp4
Connection: keep-alive
Server: Tengine
X-Tengine-Error: denied by Auth Center
Access-Control-Allow-Credentials: true
Via: cache6.cn671[,0]
Timing-Allow-Origin: *
EagleId: 78dd521a15396640284367796e
Nginx-Cache: MISS

在request headers下未发现cookie信息

**Comment by esterTion** [comment]
运营商劫持……
flash没问题吗

**Comment by Chunbear** [comment]
wow...我测试了一下，不用插件的话有些视频能看，有些会提示Y2001错误.....emmmm

**Comment by esterTion** [comment]
同样的路子监控网络看下是不是能看的没跳到ip地址服务器，挂了的都跳ip了

**Comment by Chunbear** [comment]
看了香蕉榜10个视频
1、2 无论是否使用插件都能看
均跳转到Host: 117.131.216.198:6510

3 一开始无论是否使用插件都不能看
跳转至Host: 117.131.216.198:6510
过了一段时间后，使用插件可以观看
跳转至Host: 117.131.216.199:6510

4、7、8、9、10 都不能看
跳转至Host: 117.131.216.199:6510

5 都不能看
不使用插件跳转至Host: 117.131.216.198:6510
使用插件跳转至Host: 117.131.216.199:6510

6 使用插件无法观看
跳转至Host: 117.131.216.199:6510
不使用插件可以观看
跳转至Host: 117.131.216.198:6510

应该是运营商的问题了...但是没有看出有什么规律？

**Comment by esterTion** [comment]
你先找一个确认用不了的视频，然后禁用商店扩展后 加载 [signed.zip](https://github.com/esterTion/AcFun-HTML5-Player/files/2483568/signed.zip) 
解压后的文件夹
如果可以用了我之后更新，不行的话gg，你可以去打死移动

**Comment by Chunbear** [comment]
可以用啦 测试了5个 不用或者用原来的插件不能看，新的可以看！感谢！

**Comment by SerCom-KC** [comment]
看来我只能打死移动了……
甚至出现了 http://183.215.108.4:6510/183.215.105.254:6310/video.acfun.cn/ 这样的窒息操作。🤔
