### ISSUE TITLE
macOS 下用 AirPlay 播放时音画不同步

### ISSUE THREAD

**Issue by avsdfag** [esterTion/AcFun-HTML5-Player#36]
macOS 10.14
Chrome 69.0.3497.100

使用 AirPlay 播放到 HomePod 时声音比画面慢 2 秒，使用 Mac 自带扬声器播放正常。
其他视频网站 (Youtube, Bilibili) 无论是 AirPlay 还是自带扬声器都是正常的。

有可能是 flv.js 的问题，请问还有哪些网站是使用 flv.js 的？可以的话我测试一下。

**Comment by avsdfag** [comment]
补充：firefox 和 chrome 关于 airplay 的 bug：
https://bugzilla.mozilla.org/show_bug.cgi?id=776137
https://bugs.chromium.org/p/chromium/issues/detail?id=783282

**Comment by esterTion** [comment]
flvjs本来就是b站的，奇怪

**Comment by esterTion** [comment]
所以，hls有好转么
