### ISSUE TITLE
音量条显示异常

### ISSUE THREAD

**Issue by jev001** [esterTion/AcFun-HTML5-Player#38]
加载完页面后 ,音量超过100% 音量控制器哪里显示异常了

手动调节减少至100%一下后,音量调节再次超过100%不会出现异常
![](http://ww1.sinaimg.cn/large/6359c202ly1fxknos0s81j20xm01fjro.jpg)

version:1.6.4.3

**Comment by esterTion** [comment]
下次有空再发新版

**Comment by esterTion** [comment]
已更新v1.7.0
