### ISSUE TITLE
显示正在切换就没反应了，所有视频都这样。

### ISSUE THREAD

**Issue by 992939504** [esterTion/AcFun-HTML5-Player#4]

**Comment by esterTion** [comment]
猴山给服务器加了来源判断……之前只有cookie的
chrome自动发referer，firefox不发，但是firefox用不了fetch，就没法设置referer策略
我也不认识猴山的人（

**Comment by ricekiller** [comment]
这个我也不知道是怎么搞的，如果只安装这个插件就不行，但如果再安装https://boomfun.work/tool/10里面的插件firefox就能正常播放了...

**Comment by esterTion** [comment]
57可以改得动扩展内请求了么
如果加自己改header的话，我大概需要把amo版本下架，因为这种改安全策略头算是违规的（火狐审核特别抽风）

**Comment by ricekiller** [comment]
sorry...刚才看了下上述插件，原来并没有正式上架，所以才能有你所说的违规操作吧。我只知道57版本更严格了，失效了一批插件，具体情况还真不清楚。
按我理解的话，现在的情况是如果不下架火狐就不能用，如果下架 更新就比较麻烦，因为不是我专长的领域所以就不瞎提意见了。
猴山的人估计认识的不多，毕竟跟韭菜似的换了一茬又一茬，能联系的也只是前前前前员工了(*ﾟ∇ﾟ)

**Comment by esterTion** [comment]
57失效一批是火狐换架构，作死
下架更新不麻烦，又不是google一家独大，火狐提供自分发渠道（那个直接安装一直都是自分发版）
其实违规我现在也不清楚，因为以前人工审核的时候是退回的，现在抽查，估计是抽到就退抽不到就当无事发生过，虽然还是很操蛋

我说的第一句是因为以前扩展里发出的网络请求没法被自己/其他扩展修改，发了bug只有人确认了下存在然后就没消息了，没想到居然好了（我停在ff55版继续用legacy，美滋滋）

**Comment by esterTion** [comment]
说明一下

修复方法我想到了，非常绕
这几天没时间写，我周四考完试会修
暂时先拿chrome看视频吧，或者重新把flash开开（
amo版本会下架，到时候更新之后谭一个提示，让安装独立分发版

**Comment by WangHongshuo** [comment]
> 
 ricekiller commented：
这个我也不知道是怎么搞的，如果只安装这个插件就不行，但如果再安装https://boomfun.work/tool/10 里面的插件firefox就能正常播放了，包括优酷源的视频...版本是57
--
哇，老哥稳！

**Comment by esterTion** [comment]
试了我想的方法，绕了几次还是失败了
- 转到页面内xhr：服务器不支持OPTIONS跳转
- 改为参数seek：start参数接受的不是字节是秒

给猴山发了邮件，有没有用我就不知道了

**Comment by esterTion** [comment]
更新了1.0.12，测试了下firefox57以上可以正常被修改useragent
我自己是ff55，平时我本地搭了服务器中转走免流，直接在那里面自己改了
