### ISSUE TITLE
“视频截屏”跳转至about:blank

### ISSUE THREAD

**Issue by JohnTsq** [esterTion/AcFun-HTML5-Player#46]
扩展版本：1.7.3.2
chrome版本：71.0.3578.98（正式版本） （64 位）
使用“视频截屏”功能（无论是否含弹幕）后，只能跳出about:blank页面。

同时Firefox（64.0 (64 位)）版本扩展该功能正常。

**Comment by esterTion** [comment]
是正常现象啊，能有图片就行
![qq 20181225104853](https://user-images.githubusercontent.com/7265411/50410257-b20b9000-0832-11e9-9b22-ba12548ba933.jpg)

**Comment by JohnTsq** [comment]
> 是正常现象啊，能有图片就行
> 可以右键直接复制去其他地方发消息，也可以保存
> ![qq 20181225104853](https://user-images.githubusercontent.com/7265411/50410257-b20b9000-0832-11e9-9b22-ba12548ba933.jpg)

![image](https://user-images.githubusercontent.com/28902953/50421045-2d426580-0876-11e9-9241-bb070b3c9f1a.png)
可是我的页面是一片空白···
