### ISSUE TITLE
网页加载完之后会自动播放，但是视频是暂停状态。

### ISSUE THREAD

**Issue by cookyyang** [esterTion/AcFun-HTML5-Player#47]
QQ浏览器 10.3.1(2864)
Chromium63.0.3239.26

**Comment by cookyyang** [comment]
目测是官方的H5播放器自动播放的原因？

**Comment by esterTion** [comment]
官方那个自动可以关吧

**Comment by cookyyang** [comment]
> 官方那个自动可以关吧

奇怪，自动播放是取消并没有勾选，没启用这个插件的时候确实没播放，一启用了这插件就直接双重播放了。

**Comment by cookyyang** [comment]
BFPlayer用起来没问题，不过还是喜欢你的这个。

**Comment by esterTion** [comment]
我这看着没有家在其他东西啊，搞不懂

**Comment by cookyyang** [comment]
> 我这看着没有家在其他东西啊，搞不懂

我每次只能手动点下使用旧版FLASH播放器才能不自动播放

**Comment by esterTion** [comment]
理论上可以直接干掉那个灰测配置加载，但是不是有点过分（

**Comment by esterTion** [comment]
发了个1.7.3.3，把AcPlayer干掉了

**Comment by Sokwva** [comment]
1.7.7.1依旧有这种情况，就算清空了cookies和存储也一样
