### ISSUE TITLE
chrome 73 无法播放视频

### ISSUE THREAD

**Issue by popdisk** [esterTion/AcFun-HTML5-Player#52]
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://player.acfun.cn/flash_data?vid=*** with MIME type text/plain.

可能是这个问题，参考https://www.chromium.org/Home/chromium-security/extension-content-script-fetches。

**Comment by esterTion** [comment]
？？？？？？
妈的google傻逼吧

**Comment by esterTion** [comment]
已更新1.7.5.3
