### ISSUE TITLE
播放错误Chrome	73.0.3683.103 (正式版本) （64 位）

### ISSUE THREAD

**Issue by esbackup** [esterTion/AcFun-HTML5-Player#53]
播放错误，更新之后每个视频都这样

{
  "type": "NetworkError",
  "info": "HttpStatusCodeInvalid",
  "detail": {
    "code": 403,
    "msg": "Forbidden"
  }
}
chrome网上应用店支持我也发了一份，希望大神看看帮忙解决下

**Comment by esterTion** [comment]
我这测试没问题？

**Comment by esbackup** [comment]
> 我这测试没问题？
感谢回复
可能跟我是用GreenChrome制作的chrome有关，我自己再试试，谷歌商店的支持已经删了

**Comment by esbackup** [comment]
> 我这测试没问题？

chrome记录了错误，截图：https://ws3.sinaimg.cn/large/005BYqpgly1g207jjy82qj30u01mcgya.jpg
不知道有帮助吗

**Comment by esbackup** [comment]
> 我這測試沒問題？

更新一下结果，播放错误的原因是我之前设置了 播放器核心： flv.js /mp4
改回去就没问题了，谢谢大神
