### ISSUE TITLE
https下无法播放

### ISSUE THREAD

**Issue by yaday1** [esterTion/AcFun-HTML5-Player#55]
很诡异 下午还是好的 7点半左右突然就不能用了
打开拓展就像没开一样  加载的默认播放器

**Comment by esterTion** [comment]
测试没问题

**Comment by yaday1** [comment]
我找到原因了 那天在岛上有老哥说猴山更新了https 我就把书签栏的地址换了 
http://www.acfun.cn/ 这个网址插件正常
https://www.acfun.cn/ 这个网址插件就无效

**Comment by esterTion** [comment]
草，我用的api都是http的

**Comment by esterTion** [comment]
试了下，比较惨烈
https底下ac使用的另一个新接口
然后现在浏览器扩展的访问越来越操蛋了，真的是用起来能气死人，想要搞过ac的来源限制就各种操蛋复杂
所以我有可能更新一个https强制跳转http的，也可能不管就这样放着
反正垃圾chrome赶紧去死吧

**Comment by esterTion** [comment]
写了一大段后想起来我上次在[yk](https://github.com/esterTion/Youku-HTML5-Player/commit/a9244ac4fc52fb2dda9ae50dabb651fe13a3abd9#diff-6fab85349813050b6d02ef8536bd5c61R864)里面写过类似的处理，姑且搬过来用了
