### ISSUE TITLE
chrome Version 74.0.3729.157 不能播放

### ISSUE THREAD

**Issue by yukikkl** [esterTion/AcFun-HTML5-Player#56]
之前明明能在A站播放视频但现在却不行了。
一直有这个问题，请问怎么解决？

![Untitled](https://user-images.githubusercontent.com/28840524/57979322-cc970d80-7a4e-11e9-894f-c1bd49acf42b.png)

**Comment by esterTion** [comment]
我这好着，一般是运营商问题

**Comment by yukikkl** [comment]
> 我这好着，一般是运营商问题

有能解决的方法吗？

**Comment by BurningWater9** [comment]
> > 我这好着，一般是运营商问题
> 
> 有能解决的方法吗？

登录账号就好了 不登陆没办法播放最高画质
