### ISSUE TITLE
Chrome 74.0.3729.169 Unexpected token in JSON

### ISSUE THREAD

**Issue by SystemJSN** [esterTion/AcFun-HTML5-Player#57]
如题。
貌似只出现在这两天期投稿的视频中，远古视频（三四天前的）就能播放。
![Capture](https://user-images.githubusercontent.com/17831779/59074262-7d8b0e00-887f-11e9-8e6e-399d466b9f9c.PNG)

**Comment by Sokwva** [comment]
Chrome 74.0.3729  1.79同样遇到了这样的问题
