### ISSUE TITLE
用蓝灯翻墙后感觉像是被代理了一样

### ISSUE THREAD

**Issue by zhaoaaaaa5** [esterTion/AcFun-HTML5-Player#6]
蓝灯使用的是管理系统代理，但是看视频的时候视频播放一段就会缓冲，一段十分钟的时候能缓冲两三次，有的时候缓冲1s左右就好了，有的时候会长时间缓冲

**Comment by esterTion** [comment]
找猴子，视频慢不是我的锅
我教育网也死慢
