### ISSUE TITLE
H5升级提示

### ISSUE THREAD

**Issue by scrpr** [esterTion/AcFun-HTML5-Player#60]
![图片](https://user-images.githubusercontent.com/46473171/65827515-1c6ec680-e2c4-11e9-91bc-855f0f3d565e.png)
好像最近又出现这个问题，不知道是什么原因

**Comment by Chu2koi** [comment]
我这边也一样

**Comment by winnoryder** [comment]
我这里现在不用插件打开页面就是h5播放了，好像现在a站可以免插件就h5了

**Comment by esterTion** [comment]
收到邮件后给忘了，其实之前一天看steam周榜就发现了，只是个蒙板没去掉，我顺带更新一下播放器

**Comment by esterTion** [comment]
已更新1.9.1

**Comment by Chu2koi** [comment]
![图片](https://user-images.githubusercontent.com/12667784/65955346-80d38680-e47a-11e9-98b0-41e33f56965a.png)
播放器有黑边
