### ISSUE TITLE
弹幕不加载2

### ISSUE THREAD

**Issue by Rakau** [esterTion/AcFun-HTML5-Player#62]
RT,1.9.2.1修复无效

**Comment by esterTion** [comment]
？

**Comment by esterTion** [comment]
？
拿地址说话

**Comment by Rakau** [comment]
![批注 2019-10-19 084322](https://user-images.githubusercontent.com/33389179/67135469-a9b29480-f24c-11e9-9a29-59637803a5c8.png)
![批注 2019-10-19 084245](https://user-images.githubusercontent.com/33389179/67135470-a9b29480-f24c-11e9-8c86-37a53170b0d0.png)
