### ISSUE TITLE
bug:拉取不到弹幕列表

### ISSUE THREAD

**Issue by yaday1** [esterTion/AcFun-HTML5-Player#63]
![批注 2019-11-27 233657](https://user-images.githubusercontent.com/34560089/69737186-e8523d80-116e-11ea-9d0f-34699baca10e.png)
![批注 2019-11-27 2336571](https://user-images.githubusercontent.com/34560089/69737190-e8ead400-116e-11ea-88f2-240a58819044.png)
win10 chrome78.0.3904.108  播放器右边有黑边 有时候没有

**Comment by esterTion** [comment]
黑边懒得管了，新版布局挺坑的
怕是再更新几次我就快弃坑了（bushi
弹幕刚更新了修复
