### ISSUE TITLE
老番视频源，包括iqiyi，pptv...无法解析

### ISSUE THREAD

**Issue by ricekiller** [esterTion/AcFun-HTML5-Player#8]
详见此列表：http://www.acfun.cn/v/list144/index.htm#page=1;date=0;sort=2;asc=1
以前视频源相当混乱，杂七杂八的视频源都有，目前用插件都无法解析。
271（也是无法观看，用硕鼠可以解析）：http://www.acfun.cn/bangumi/ab5018327_27449_194997
乐视（标注的是letv2，无法观看，硕鼠解析失败，估计乐视是真炸了）：http://www.acfun.cn/bangumi/ab5018352_27468_195330
pptv：http://www.acfun.cn/bangumi/ab5018748_27862_204080
优酷（这里显示youku2）：http://www.acfun.cn/bangumi/ab5018421_27536_198421
暂时找到这些，视频源太老了，我都不想吐槽了，而且这个番剧的界面那叫一个难找。
看的人估计也没多少|-` )感觉也就我这么闲找这些问题了。

**Comment by esterTion** [comment]
youku2没区别
这个letv2怎么里面还有个新浪地址的，惊了

**Comment by esterTion** [comment]
哇，这列表这页好老啊（

**Comment by esterTion** [comment]
大概说一下
我这边以前有的api都过期了
目前只准备对有sina备用地址的走sina，其他我也懒得写了

**Comment by esterTion** [comment]
已更新1.0.15

**Comment by ricekiller** [comment]
哇，安装了更新，一堆视频复活了。
感觉剩下的也不用抢救了，现在就挺不错的了。
