### ISSUE TITLE
firfox,报播放错误，全职猎人，优酷

### ISSUE THREAD

**Issue by dao000qiao** [esterTion/AcFun-HTML5-Player#9]
播放错误
{
  "type": "NetworkError",
  "info": "HttpStatusCodeInvalid",
  "detail": {
    "code": 403,
    "msg": "Forbidden"
  }
}
BUG:
固定为快一半的时候，看的是全职猎人 重置版（优酷版权），初步怀疑是中间的广告，结尾的时候也有一个，也有可能是缓存了那么多停下，继续缓存的时候出现问题
FIRFOX

**Comment by esterTion** [comment]
刷新就好么
优酷老毛病，视频地址有效期短，莫名失效

**Comment by dao000qiao** [comment]
刷新可以好，基本上可以确定了，放置PLAY一会等他停止加载，播放到附近要加载的时候就会报错，应该可以修复的吧

**Comment by esterTion** [comment]
这个挺操蛋的，yk播放器里面我是设置403就获取新地址，ac里面源太多了写重试逻辑有点麻烦 ~~（懒）~~

**Comment by esterTion** [comment]
已更新1.0.15
